[versions]
jdk = "25"
jvmram = "1.0.3"
slf4j = "2.0.17"

protobuf = "3.25.8"
grpc = "1.78.0"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

jspecify = "org.jspecify:jspecify:1.0.0"

grpc-bom = { module = "io.grpc:grpc-bom", version.ref = "grpc" }

dimension = "com.github.alexvas:dimension-di:26.1.11"

[plugins]
protobuf = "com.google.protobuf:0.9.6"
