syntax = "proto3";

option java_multiple_files = true;
option java_package = "jvmram.proto";
option java_outer_classname = "JvmRamProto";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

package jvmram;

service AppBackend {
  rpc GetExplicitlyFollowingPids (google.protobuf.Empty) returns (PidList);
  rpc SetFollowingPids (PidList) returns (google.protobuf.Empty);
  rpc AreChildrenProcessesIncluded (google.protobuf.Empty) returns (ChildrenProcessIncludedResponse);
  rpc IncludeChildrenProcesses (google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc ExcludeChildrenProcesses (google.protobuf.Empty) returns (google.protobuf.Empty);

  rpc GetApplicableMetrics (google.protobuf.Empty) returns (ApplicableMetricsResponse);

  rpc SetVisible (SetVisibleRequest) returns (google.protobuf.Empty);
  rpc SetInvisible (SetInvisibleRequest) returns (google.protobuf.Empty);

  rpc RefreshAvailableJvmProcesses (google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc ListenJvmProcessList (google.protobuf.Empty) returns (stream JvmProcessListResponse);
  rpc ListenGraphQueues (google.protobuf.Empty) returns (stream GraphQueues);

  rpc TriggerGc (Pid) returns (google.protobuf.Empty);

  /* RPC between UI and Rust backend: */
  rpc DumpHeap (DumpRequest) returns (DumpResponse);
  /* RPC between Rust and JVM backends: */
  rpc DumpHeapJvm (DumpJvmRequest) returns (google.protobuf.Empty);

  /* RPC between UI and Rust backend: */
  rpc DumpThread (DumpRequest) returns (DumpResponse);
  /* RPC between Rust and JVM backends: */
  rpc DumpThreadJvm (DumpJvmRequest) returns (google.protobuf.Empty);
}

message Pid {
  int32 pid = 1;
}

message ProcInfo {
  int32 pid = 1;
  string display_name = 2;
  repeated int32 children = 3;
}

message PidList {
  repeated Pid pids = 1;
}

message JvmProcessListResponse {
  repeated ProcInfo infos = 1;
}

message DumpRequest {
  int32 pid = 1;
  string main = 2;
  string comment = 3;
}

message DumpJvmRequest {
  int32 pid = 1;
  string output_file_path = 2;
}

message DumpResponse {
  string file_name = 1;
}

enum MetricType {
  RSS = 0;
  PSS = 1;
  USS = 2;
  WS = 3;
  PB = 4;
  HEAP_USED = 5;
  HEAP_COMMITTED = 6;
  OLD_GEN_MAX = 7;
  OLD_GEN_COMMITTED = 8;
  OLD_GEN_USED = 9;
  NMT_USED = 10;
  NMT_COMMITTED = 11;
  BUFFER_TOTAL = 12;
}

message GraphPoint {
  /* время в десятых долях секунды с момента старта приложения */
  int32 zehntel = 1;
  int32 kilobytes = 2;
}

message GraphQueue {
  MetricType metric_type = 1;
  repeated GraphPoint points = 2;
}

message GraphQueues {
  int32 pid = 1;
  /* момент старта приложения */
  google.protobuf.Timestamp app_start = 2;
  repeated GraphQueue queues = 3;
}

message ApplicableMetricsResponse {
  repeated MetricType types = 1;
}

message SetVisibleRequest {
  MetricType metric_type = 1;
}

message SetInvisibleRequest {
  MetricType metric_type = 1;
}

message ChildrenProcessIncludedResponse {
  bool areIncluded = 1;
}
